### PR TITLE
docs: mention `arbitrary(bound = "...")` container attribute in trait docs

### PR DESCRIPTION
**Pull request by benluelo**

### CODE REVIEW

**Review by fitzgen — APPROVED** [review]
Thanks!

**Comment by fitzgen** [comment]
Looks like the example isn't compiling.

**Comment by benluelo** [comment]
my bad, - forgot to pass --all-features to cargo test, and didn't thoroughly check the output. should be passing now!

**Comment by fitzgen** [comment]
Thanks!

**Pull request merged**
