### PR TITLE
Bump to version 1.0.0-rc1!

### PR DESCRIPTION
**Pull request by fitzgen**
r? @Manishearth 

After merging I'll publish this to crates.io

### CODE REVIEW

**Comment by nagisa** [comment]
Please avoid making pre-release versions. Cargo is very bad at handling them. See https://github.com/rust-lang/cargo/issues/2222.

Lets just keep releasing `0.x+1` versions until we are ready to cut a 1.0.

**Comment by nagisa** [comment]
Or more specifically: https://github.com/rust-lang/cargo/issues/7676

**Comment by Manishearth** [comment]
Yeah let's not do a prerelease version.

**Comment by fitzgen** [comment]
Alright!

**Pull request closed without merging**
