### PR TITLE
Bump to version 0.3.0

### LINKED ISSUE #19: Tracking issue for 0.3.0 release
So we have some nice improvements to this crate, and I think everything has technically been compatible with a 0.2.X release but I think it is a good time to revisit some of the public API and trait designs and make a 0.3.0 release. I figured it would be good to open an issue to talk about what we might want in it.

## TODO

* [x] Fill out public API doc comments, and add examples to each of them
* [x] Better `Arbitrary` for `String` implementation (#17)
* [x] Should `Arbitrary` have `Debug` as a super trait? (#7)
* [x] Should `Arbitrary` have `Clone` as a super trait? This would allow easier/better shrinking implementations (e.g. for various collections)
* [x] Refactor `Unstructured` to look more like [`FuzzedDataProvider`](https://github.com/rust-fuzz/libfuzzer-sys/blob/master/libfuzzer/utils/FuzzedDataProvider.h)? In particular, maybe we should get lengths from the end of the buffer like that does.
* [x] Add `Arbitrary::arbitrary_take_rest` methods to consume the rest of an `Unstructured`. (#18)
* [x] Add `Arbitrary::size_hint` and refactor `Unstructured::container_size` into `Unstructured::collection_len`, as discussed in #18.
* [x] Add a `fn arbitrary<A: Arbitrary>(&mut self) -> Result<A, Self::Error>` helper method to `Unstructured` to shorten invoking nested-arbitrary calls, so you can just do `let foo = u.arbitrary()?;` and let type inference figure things out for you?

As we surface more things to be done for 0.3.0 in the comments, I'll add them to this list, so that we have a single place for everything.

------------------------------

+cc @Manishearth: what do you think? Anything we should add to or remove from this list?

### PR DESCRIPTION
**Pull request by fitzgen**
Fixes #19

### CODE REVIEW

**Comment by fitzgen** [comment]
Gah I can't publish because I'm not an owner of `derive_arbitrary` on crates.io. @nagisa would you mind adding me as an owner? Thanks!

**Comment by Manishearth** [comment]
I'm also okay with releasing this as arbitrary-derive instead, that's the typical naming scheme anyway. We can update the original with a redirect later

**Comment by nagisa** [comment]
Sent out the invite.

**Comment by fitzgen** [comment]
Thank you!

**Comment by fitzgen** [comment]
Published!

**Pull request merged**
